dist: xenial
git:
  depth: 3
language: go
go:
  - "1.x"
  - "1.10.x"
before_script:
  - go get golang.org/x/lint/golint
script:
  - gofmt -d -e -l -s .
  - golint -set_exit_status ./...
  - go test -v ./...
