dist: xenial
git:
  depth: 3
language: go
go:
  - "master"
  - "1.12.x"
  - "1.11.x"
env:
  global:
    - GO111MODULE=on
before_script:
  - go get golang.org/x/lint/golint
  - go mod download -json
script:
  - gofmt -d -e -l -s .
  - golint -set_exit_status ./...
  - go test -v ./...
