name: Build
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check formatting
        run: gofmt -d -e -l -s .
      - name: Build and test
        run: |
          go test -v -race ./...
          go build ./cmd/walker
          go build ./cmd/reporter
