name: Build
on:
  pull_request:
  push:
    branches: [ main, test/gha ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: Install golint
        run: go install golang.org/x/lint/golint@latest
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Downnlaod Go modules
        run: go mod download -json
      - name: Check formatting
        run: gofmt -d -e -l -s .
      - name: Lint
        run: golint -set_exit_status ./...
      - name: Build and test
        run: |
          go test -v ./...
          go build ./cmd/walker
          go build ./cmd/reporter
